# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  AZURE_CONTAINER_REGISTRY: "java1234"
  CONTAINER_NAME: "project"
  RESOURCE_GROUP: "final-resource"
  CLUSTER_NAME: "test-cluster"
  MANIFEST_PATH: "/deployement.yml"
  



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
   

      # Logs in with your Azure credentials
      
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  




    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
          resource-group: final-resource
          cluster-name: test-cluster

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v4
      with:
          manifests: |
            /deployment.yml
          images: |
            java1234.azurecr.io/project1:latest
      
      
      
  




    
        

